Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - app/controllers/graphql_controller.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
    - app/controllers/graphql_controller.rb
