# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    container: ruby:2.7.1-alpine

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: assetmanagement
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Install OS dependencies
      run: apk add --update build-base tzdata postgresql-dev
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run Rubocop
      run: bundle exec rubocop
    - name: Run Reek
      run: bundle exec reek
    - name: Migrate DB
      run: bundle exec rails db:migrate:reset RAILS_ENV=test
    - name: Run rspec
      run: bundle exec rspec
